# Generated by Django 4.2.23 on 2025-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("total_samples", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="foodfeedbacksample",
            name="is_correct",
            field=models.BooleanField(
                blank=True, help_text="آیا پیش\u200cبینی مدل درست بوده است؟", null=True
            ),
        ),
    ]
